env:
  CIRRUS_CLONE_DEPTH: 3
  LIBPCAP_GIT: https://github.com/the-tcpdump-group/libpcap
  AUTOCONF_WARNINGS: no-obsolete

freebsd_task:
  name: freebsd-amd64
  only_if: $CIRRUS_BRANCH != 'coverity_scan'
  freebsd_instance:
    cpu: 1
    memory: 2G
    image_family: freebsd-13-4
  env:
    IGNORE_OSVERSION: yes
    MATRIX_CC: clang17 gcc13
  script:
    - pkg install -qy autoconf gcc13 llvm17
    - pkg install -qy git-tiny # for build_matrix.sh
    - git -C .. clone --depth ${CIRRUS_CLONE_DEPTH} --branch=master --quiet ${LIBPCAP_GIT}
    - ./build_matrix.sh

linux_task:
  name: linux-amd64
  only_if: $CIRRUS_BRANCH != 'coverity_scan'
  container:
    cpu: 1
    memory: 1G
    image: ubuntu:24.04
  env:
    LANG: C
  script:
    - apt-get -qy update >/dev/null
    - apt-get -qy install git binutils-dev >/dev/null # for "make releasecheck"
    - apt-get -qy install autoconf make gcc libpcap-dev >/dev/null
    - apt-get -qy install shellcheck >/dev/null
    - ./autogen.sh
    # build the Makefile
    - ./configure --quiet --without-libnids --without-libosipparser2 --without-libooh323c
    - make releasecheck
    - make whitespacecheck
    - make shellcheck

macos_task:
  name: macos-aarch64
  only_if: $CIRRUS_BRANCH != 'coverity_scan'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma # last 3 versions of Xcode
  env:
    MAKEFLAGS: '-j 4' # macOS VMs run on 4 cores
  script:
    - brew update >/dev/null
    - git -C .. clone --depth ${CIRRUS_CLONE_DEPTH} --branch=master --quiet ${LIBPCAP_GIT}
    - ./build_matrix.sh

coverity_task:
  name: Coverity Scan
  only_if: $CIRRUS_BRANCH == 'coverity_scan'
  container:
    cpu: 1
    memory: 2G
    image: ubuntu:24.04
  env:
    # libnids-dev -> tzdata -> debconf
    DEBIAN_FRONTEND: noninteractive
    LANG: C
    COVERITY_SCAN_PROJECT_NAME: $CIRRUS_REPO_FULL_NAME
    COVERITY_SCAN_TOKEN: ENCRYPTED[1f7a6aa7e3fd93d9556938b29df39e43e510fc3083f41bcd2283c7a7afe62dd31d00e19717d64d955c5fdd7916451d27]
    COVERITY_SCAN_BUILD_COMMAND_PREPEND: ./configure --enable-instrument-functions
    COVERITY_SCAN_BUILD_COMMAND: make
  script:
    - apt-get -qy update >/dev/null
    - apt-get -qy install libpcap-dev libnids-dev libosip2-dev autoconf make gcc binutils-dev >/dev/null
    - apt-get -qy install git curl wget ruby rubygems ruby-json >/dev/null # for the coverity script
    - apt list --installed 'lib*-dev'
    - ./autogen.sh
    - ./.ci-coverity-scan-build.sh
