env:
  CIRRUS_CLONE_DEPTH: 3
  LIBPCAP_GIT: https://github.com/the-tcpdump-group/libpcap
  MAKEFLAGS: '-j 2'

freebsd_task:
  name: freebsd-amd64
  only_if: $CIRRUS_BRANCH != 'coverity_scan'
  freebsd_instance:
    cpu: 2
    memory: 2G
    matrix:
      - image_family: freebsd-12-4
      - image_family: freebsd-13-2
  env:
    IGNORE_OSVERSION: yes
    MATRIX_CC: clang15 gcc12
  script:
    - pkg install -qy autoconf gcc12 llvm15
    - pkg install -qy git-tiny # for build_matrix.sh
    - git -C .. clone --depth ${CIRRUS_CLONE_DEPTH} --branch=master --quiet ${LIBPCAP_GIT}
    - ./build_matrix.sh

linux_task:
  name: linux-amd64
  only_if: $CIRRUS_BRANCH != 'coverity_scan'
  container:
    cpu: 2
    memory: 2G
    image: ubuntu:22.04
  env:
    DEBIAN_FRONTEND: noninteractive # libnids-dev -> tzdata -> debconf
    MATRIX_CC: gcc-12 clang-15
  script:
    - apt-get -qy update >/dev/null
    - apt-get -qy install libpcap-dev libnids-dev libosip2-dev autoconf make clang-15 gcc-12 >/dev/null
    - apt-get -qy install flex bison libdbus-1-dev libbluetooth-dev libnl-genl-3-dev libibverbs-dev >/dev/null # for libpcap
    - apt-get -qy install git bc >/dev/null # for build_matrix.sh and build.sh
    - apt-get -qy install shellcheck >/dev/null
    - apt list --installed 'lib*-dev'
    - git -C .. clone --depth ${CIRRUS_CLONE_DEPTH} --branch=master --quiet ${LIBPCAP_GIT}
    - ./autogen.sh
    - CC=gcc-12 ./configure --quiet # build the Makefile
    - make releasecheck
    - make whitespacecheck
    - make shellcheck
    - ./build_matrix.sh

macos_task:
  name: macos-aarch64
  only_if: $CIRRUS_BRANCH != 'coverity_scan'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.1 # macOS 13 with Xcode 14.1
  env:
    MAKEFLAGS: '-j 4' # macOS VMs run on 4 cores
  script:
    - brew update >/dev/null
    - git -C .. clone --depth ${CIRRUS_CLONE_DEPTH} --branch=master --quiet ${LIBPCAP_GIT}
    - ./build_matrix.sh

coverity_task:
  name: Coverity Scan
  only_if: $CIRRUS_BRANCH == 'coverity_scan'
  container:
    cpu: 2
    memory: 2G
    image: ubuntu:22.04
  env:
    DEBIAN_FRONTEND: noninteractive
    COVERITY_SCAN_PROJECT_NAME: $CIRRUS_REPO_FULL_NAME
    COVERITY_SCAN_TOKEN: ENCRYPTED[1f7a6aa7e3fd93d9556938b29df39e43e510fc3083f41bcd2283c7a7afe62dd31d00e19717d64d955c5fdd7916451d27]
    COVERITY_SCAN_BUILD_COMMAND_PREPEND: ./configure --enable-instrument-functions
    COVERITY_SCAN_BUILD_COMMAND: make
  script:
    - apt-get -qy update >/dev/null
    - apt-get -qy install libpcap-dev libnids-dev libosip2-dev autoconf make gcc binutils-dev >/dev/null
    - apt-get -qy install git curl wget ruby rubygems ruby-json >/dev/null # for the coverity script
    - apt list --installed 'lib*-dev'
    - ./autogen.sh
    - ./.ci-coverity-scan-build.sh
